name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Archive production artifacts
        run: tar czvf out.tar.gz out/
